package ArduinoML.behavior;

/*Generated by MPS */


public class Actuator_BehaviorDescriptor extends Brick_BehaviorDescriptor {
  public Actuator_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Actuator";
  }
}
