package ArduinoML.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;
  public static Object propertyMacro_GetPropertyValue_96698208123630550(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xcf43e94a8bf24001L, 0xbc872345e11e4770L, 0x1578a8209959438L, 0x1578a82099e72cfL, "init_state")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_96698208123416629(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xcf43e94a8bf24001L, 0xbc872345e11e4770L, 0x1578a820994cf1cL, 0x1578a8209959428L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_96698208123505562(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xcf43e94a8bf24001L, 0xbc872345e11e4770L, 0x1578a820994cf1cL, 0x1578a8209959428L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_96698208123678389(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xcf43e94a8bf24001L, 0xbc872345e11e4770L, 0x1578a82099e721cL, 0x1578a82099e726eL, "actuator")), MetaAdapterFactory.getProperty(0xcf43e94a8bf24001L, 0xbc872345e11e4770L, 0x1578a820994cf1cL, 0x1578a8209959428L, "pin"));
  }
  public static Iterable<SNode> sourceNodesQuery_96698208123606105(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xcf43e94a8bf24001L, 0xbc872345e11e4770L, 0x1578a8209959438L, 0x1578a8209959445L, "bricks"));
  }
}
